spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23141/seiso?autoReconnect=true
    username: seiso
    password: seiso
    maximum-pool-size: 10
    minimum-idle: -1
    # TODO Add other data source settings here
  jpa:
    openInView: true
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  data:
    rest:
      base-path: /api

management:
  context-path: /admin

logging:
#  file: /var/log/seiso/seiso.log
  level:
    com.expedia.seiso: TRACE
    org.springframework: INFO

# IMPORTANT: This is a potential security risk, so use discretion.
# The admin panel currently assumes that endpoints.health.sensitive is false.
endpoints:
  health:
    sensitive: false
