spring:
  main:
    web-environment: true
    show-banner: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # Note: Change the port if using Vagrant setup with non-default 'host' port-forwarding
    url: jdbc:mysql://localhost:3306/seiso?autoReconnect=true
    username: root
    password: 
    # TODO Add other data source settings here
  jpa:
    openInView: true
    database: MYSQL
    show-sql: false
    generate-ddl: false
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  rabbitmq:
    host: 192.168.33.10
    port: 5672
    username: seiso
    password: seiso

logging:
#  file: /var/log/seiso/seiso.log
  level:
    com.expedia.seiso: TRACE
    org.springframework: INFO

security:
  basic:
    enabled: false

server:
  port: 8443
  session-timeout: 1200
  ssl:
    key-store: classpath:keystore-dev.jks
    key-store-password: seisoapi

custom:
  # No trailing slash!
  base-uri: http://localhost:8443
  change-notification-exchange: seiso.notifications.v2
  action-request-exchange: seiso.action_requests.v2
  seyren-base-uri: http://seyren.example.com
